project_id = "tpiaceyooekujzsvsyid"

[functions.processar-autos]
verify_jwt = true

[functions.gerar-resumos]
verify_jwt = true

[functions.delete-user]
verify_jwt = false

[functions.test-ai-connection]
verify_jwt = false

[functions.check-import-status]
verify_jwt = true

[functions.regerar-campo-pdf]
verify_jwt = true
