// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0";

// src/lib/mcp/tools/list-laudos.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_laudos_default = defineTool({
  name: "list_laudos",
  title: "Listar laudos",
  description: "Lista os laudos periciais do usu\xE1rio autenticado (id, t\xEDtulo, reclamante, processo, status, datas). N\xE3o retorna o conte\xFAdo completo do laudo.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de laudos (padr\xE3o 20)."),
    status: z.string().optional().describe("Filtrar por status (ex: rascunho, finalizado)."),
    search: z.string().optional().describe("Busca em t\xEDtulo, reclamante ou n\xFAmero do processo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("laudos").select(
      "id,title,reclamante,reclamada,processo_numero,status,tipo_laudo,data_pericia,updated_at,created_at"
    ).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    if (search) {
      q = q.or(
        `title.ilike.%${search}%,reclamante.ilike.%${search}%,processo_numero.ilike.%${search}%`
      );
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { laudos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-laudo.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_laudo_default = defineTool2({
  name: "get_laudo",
  title: "Obter laudo",
  description: "Retorna todos os campos de um laudo pericial do usu\xE1rio autenticado (dados do processo, v\xEDtima, hist\xF3rico, exames, nexo, conclus\xE3o, quesitos).",
  inputSchema: {
    laudo_id: z2.string().uuid().describe("UUID do laudo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ laudo_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("laudos").select("*").eq("id", laudo_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Laudo n\xE3o encontrado" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { laudo: data }
    };
  }
});

// src/lib/mcp/tools/list-pericias-previdenciarias.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_pericias_previdenciarias_default = defineTool3({
  name: "list_pericias_previdenciarias",
  title: "Listar per\xEDcias previdenci\xE1rias",
  description: "Lista as per\xEDcias previdenci\xE1rias do usu\xE1rio autenticado, opcionalmente filtradas por pauta.",
  inputSchema: {
    pauta_id: z3.string().uuid().optional().describe("Filtrar por pauta."),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ pauta_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("prev_pericias").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (pauta_id) q = q.eq("pauta_id", pauta_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { pericias: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-financeiro.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_financeiro_default = defineTool4({
  name: "list_financeiro",
  title: "Listar lan\xE7amentos financeiros",
  description: "Lista os lan\xE7amentos financeiros do usu\xE1rio autenticado (honor\xE1rios, despesas, status de pagamento).",
  inputSchema: {
    status: z4.string().optional().describe("Filtrar por status (ex: pendente, pago)."),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("financeiro").select("*").order("data_vencimento", { ascending: false, nullsFirst: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { lancamentos: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tpiaceyooekujzsvsyid";
var mcp_default = defineMcp({
  name: "tenorio-mpj-mcp",
  title: "Ten\xF3rio MPJ \u2014 MCP",
  version: "0.1.0",
  instructions: "Ferramentas do sistema Ten\xF3rio MPJ (laudos m\xE9dico-periciais). Use `list_laudos` e `get_laudo` para consultar laudos trabalhistas, `list_pericias_previdenciarias` para o m\xF3dulo previdenci\xE1rio e `list_financeiro` para lan\xE7amentos. Todas as opera\xE7\xF5es rodam como o usu\xE1rio autenticado e respeitam RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_laudos_default, get_laudo_default, list_pericias_previdenciarias_default, list_financeiro_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
